"""Idempotent, self-healing schema migrations run at app startup.

Why this exists: the wa_ tables were originally created by a one-time Supabase
SQL script, but the models keep gaining columns/tables faster than that script
gets re-run by hand — which surfaced as runtime errors like
``column wa_advocates.email does not exist``. Running these IF-NOT-EXISTS
statements on every boot keeps the live schema in sync with the models with no
manual step. Every statement is idempotent and runs in its own transaction, so
one failure can't block the rest and a fully-migrated DB is a cheap no-op.

The app connects as the table OWNER (Supabase ``postgres``), so it has DDL
rights and BYPASSES the (non-forced) RLS enabled below. We never FORCE RLS.
"""
import logging

from sqlalchemy import text as sa_text

from database.models import db

logger = logging.getLogger("whatsapp_bot")

# Ordered, idempotent DDL. CREATE TABLE handles a brand-new DB; the ALTERs heal
# an older DB that was created before a column existed; indexes + RLS are safe
# to re-run. Keep in sync with whatsapp_bot/schema.sql (the human reference).
_STATEMENTS = [
    """create table if not exists public.wa_companies (
        id              bigint generated by default as identity primary key,
        name            text not null,
        normalized_name text not null unique,
        created_at      timestamptz not null default now()
    )""",
    """create table if not exists public.wa_users (
        id                bigint generated by default as identity primary key,
        phone             text not null unique,
        profile_name      text,
        first_name        text,
        last_name         text,
        email             text,
        terms_accepted_at timestamptz,
        last_language     text not null default 'en',
        is_blocked        boolean not null default false,
        created_at        timestamptz not null default now(),
        updated_at        timestamptz not null default now()
    )""",
    """create table if not exists public.wa_conversations (
        id          bigint generated by default as identity primary key,
        user_id     bigint not null unique references public.wa_users(id),
        flow        text,
        step        text,
        data        jsonb not null default '{}'::jsonb,
        updated_at  timestamptz not null default now()
    )""",
    """create table if not exists public.wa_outbound_messages (
        id          bigint generated by default as identity primary key,
        to_phone    text not null,
        body        text,
        content_sid text,
        twilio_sid  text,
        status      text,
        error       text,
        created_at  timestamptz not null default now()
    )""",
    """create table if not exists public.wa_inbound_messages (
        id               bigint generated by default as identity primary key,
        message_sid      text not null unique,
        from_phone       text not null,
        profile_name     text,
        body             text,
        num_media        integer not null default 0,
        parsed_command   text,
        response_summary text,
        processing_ms    integer,
        error            text,
        created_at       timestamptz not null default now()
    )""",
    """create table if not exists public.wa_advocates (
        id          bigint generated by default as identity primary key,
        user_id     bigint not null references public.wa_users(id),
        company_id  bigint not null references public.wa_companies(id),
        email       text,
        role_title  text,
        status      text not null default 'active',
        created_at  timestamptz not null default now(),
        updated_at  timestamptz not null default now()
    )""",
    """create table if not exists public.wa_company_requests (
        id                  bigint generated by default as identity primary key,
        candidate_user_id   bigint not null references public.wa_users(id),
        company_name_raw    text not null,
        normalized_name     text,
        resolved_company_id bigint references public.wa_companies(id),
        reason              text not null,
        status              text not null default 'open',
        created_at          timestamptz not null default now()
    )""",
    """create table if not exists public.wa_applications (
        id                bigint generated by default as identity primary key,
        candidate_user_id bigint not null references public.wa_users(id),
        company_id        bigint not null references public.wa_companies(id),
        role_query        text,
        job_posting_url   text,
        resume_path       text,
        resume_filename   text,
        status            text not null default 'submitted',
        created_at        timestamptz not null default now(),
        updated_at        timestamptz not null default now()
    )""",
    """create table if not exists public.wa_application_recipients (
        id             bigint generated by default as identity primary key,
        application_id bigint not null references public.wa_applications(id),
        advocate_id    bigint not null references public.wa_advocates(id),
        email          text,
        emailed_at     timestamptz,
        email_status   text,
        error          text,
        created_at     timestamptz not null default now()
    )""",
    """create table if not exists public.wa_contact_messages (
        id         bigint generated by default as identity primary key,
        user_id    bigint references public.wa_users(id),
        name       text,
        phone      text,
        email      text,
        message    text not null,
        handled_at timestamptz,
        created_at timestamptz not null default now()
    )""",
    # ---- heal older tables that predate later columns ----
    "alter table public.wa_companies add column if not exists careers_url text",
    "alter table public.wa_advocates add column if not exists email text",
    "alter table public.wa_advocates add column if not exists referral_link text",
    "alter table public.wa_advocates add column if not exists role_title text",
    "alter table public.wa_advocates add column if not exists advocate_name text",
    # Person-less curated referral links (no advocate user) need a nullable user_id.
    "alter table public.wa_advocates alter column user_id drop not null",
    "alter table public.wa_application_recipients add column if not exists email text",
    "alter table public.wa_application_recipients add column if not exists approval_token text",
    "alter table public.wa_application_recipients add column if not exists approved_at timestamptz",
    "alter table public.wa_application_recipients add column if not exists denied_at timestamptz",
    "alter table public.wa_applications add column if not exists job_description text",
    # ---- seed known careers pages, keyed by normalized_name (fills NULL only,
    # so admin edits via /admin → WhatsApp → Companies are never overwritten;
    # all URLs verified live 2026-07-11, updated 2026-07-13) ----
    """update public.wa_companies c set careers_url = v.url
        from (values
            ('google',        'https://careers.google.com/'),
            ('meta',          'https://www.metacareers.com/'),
            ('microsoft',     'https://careers.microsoft.com/'),
            ('amazon',        'https://www.amazon.jobs/'),
            ('apple',         'https://jobs.apple.com/'),
            ('wix',           'https://www.wix.com/jobs'),
            ('monday.com',    'https://monday.com/careers'),
            ('fiverr',        'https://www.fiverr.com/jobs'),
            ('checkout.com',  'https://www.checkout.com/careers'),
            ('taboola',       'https://www.taboola.com/careers'),
            ('appcharge',     'https://appcharge.com/careers'),
            ('appsflyer',     'https://www.appsflyer.com/careers/'),
            ('aqua security', 'https://www.aquasec.com/about-us/careers/'),
            ('armis',         'https://www.armis.com/armis-careers/'),
            ('aryon security', 'https://www.aryon.security/careers'),
            ('at&t israel r&d center', 'https://il.att.com/'),
            ('autofleet',     'https://autofleet.io/careers'),
            ('beyondtrust',   'https://www.beyondtrust.com/careers'),
            ('biocatch',      'https://www.biocatch.com/cybersecurity-careers'),
            ('cato networks', 'https://www.catonetworks.com/careers/'),
            ('check point',   'https://careers.checkpoint.com/'),
            ('checkpoint',    'https://careers.checkpoint.com/'),
            ('coralogix',     'https://coralogix.com/careers/'),
            ('credito',       'https://credito.co.il/jobs/'),
            ('crowdstrike',   'https://www.crowdstrike.com/careers/'),
            ('cycode',        'https://cycode.com/careers/'),
            ('cyera',         'https://www.cyera.com/careers'),
            ('deloitte',      'https://careers.deloitte.co.il/'),
            ('dream security', 'https://dreamgroup.com/careers'),
            ('entitle',       'https://www.beyondtrust.com/careers'),
            ('forter',        'https://www.forter.com/careers/'),
            ('frontegg',      'https://frontegg.com/careers'),
            ('global e',      'https://www.global-e.com/careers'),
            ('gong',          'https://www.gong.io/careers/'),
            ('human security', 'https://www.humansecurity.com/company/careers/'),
            ('imagen',        'https://imagen-ai.com/careers/'),
            ('interaction (adler chomsky)', 'https://www.comeet.com/jobs/interaction/04.00A'),
            ('istra research', 'https://www.istraresearch.com/careers'),
            ('jfrog',         'https://jfrog.com/careers/'),
            ('lemonade',      'https://makers.lemonade.com/'),
            ('mobileye',      'https://careers.mobileye.com/'),
            ('moon active',   'https://www.moonactive.com/careers/'),
            ('moonactive',    'https://www.moonactive.com/careers/'),
            ('natural intelligence', 'https://www.naturalint.com/jobs'),
            ('nexxen',        'https://www.nexxen.com/careers'),
            ('nice',          'https://www.nice.com/careers'),
            ('nvidia',        'https://www.nvidia.com/en-us/about-nvidia/careers/'),
            ('pagaya',        'https://pagaya.com/careers'),
            ('palo alto networks', 'https://jobs.paloaltonetworks.com/'),
            ('papaya gaming', 'https://careers.papayagaming.com/'),
            ('payoneer',      'https://careers.payoneer.com/'),
            ('perion',        'https://www.perion.com/careers/'),
            ('personetics',   'https://personetics.com/careers/'),
            ('plus500',       'https://careers.plus500.com/'),
            ('pontera',       'https://pontera.com/careers'),
            ('qodo',          'https://www.qodo.ai/careers/'),
            ('radware',       'https://www.radware.com/careers/'),
            ('rapyd',         'https://www.rapyd.net/company/careers/'),
            ('riskified',     'https://www.riskified.com/careers/'),
            ('riverside',     'https://careers.riverside.com/'),
            ('scaleops',      'https://scaleops.com/careers'),
            ('sciplay',       'https://sciplay.com/careers/'),
            ('sela',          'https://selacloud.com/careers'),
            ('sentra',        'https://sentra.io/careers'),
            ('sunflower',     'https://www.comeet.com/jobs/sunflower/AA.009'),
            ('superplay',     'https://www.superplay.co/careers/'),
            ('team8',         'https://team8.vc/careers'),
            ('tenable',       'https://www.tenable.com/careers'),
            ('thales',        'https://careers.thalesgroup.com/'),
            ('unity',         'https://unity.com/careers'),
            ('varonis',       'https://www.varonis.com/careers'),
            ('via',           'https://ridewithvia.com/careers'),
            ('viber',         'https://www.viber.com/en/careers/'),
            ('walmart',       'https://careers.walmart.com/'),
            ('webbing',       'https://webbingsolutions.com/careers/'),
            ('weka.io',       'https://www.weka.io/company/careers/')
        ) as v(norm, url)
        where c.normalized_name = v.norm and c.careers_url is null""",
    # ---- indexes ----
    """create index if not exists ix_wa_inbound_from_created
        on public.wa_inbound_messages (from_phone, created_at)""",
    # an advocate may register several work emails per company → unique per email
    "drop index if exists uq_wa_advocates_user_company",
    """create unique index if not exists uq_wa_advocates_user_company_email
        on public.wa_advocates (user_id, company_id, email)""",
    # fast lookup of a referral by its approval-link token
    """create unique index if not exists uq_wa_recipient_approval_token
        on public.wa_application_recipients (approval_token)""",
    # ---- lock the PII tables out of the anon PostgREST API (owner bypasses) ----
    "alter table public.wa_companies             enable row level security",
    "alter table public.wa_users                 enable row level security",
    "alter table public.wa_conversations         enable row level security",
    "alter table public.wa_outbound_messages     enable row level security",
    "alter table public.wa_inbound_messages      enable row level security",
    "alter table public.wa_advocates             enable row level security",
    "alter table public.wa_company_requests      enable row level security",
    "alter table public.wa_applications          enable row level security",
    "alter table public.wa_application_recipients enable row level security",
    "alter table public.wa_contact_messages       enable row level security",
]


def run_migrations(app):
    """Apply the idempotent DDL. Never raises — a failed statement is logged and
    skipped so a migration hiccup can't take the whole app down at boot."""
    with app.app_context():
        applied, failed = 0, 0
        for stmt in _STATEMENTS:
            try:
                db.session.execute(sa_text(stmt))
                db.session.commit()
                applied += 1
            except Exception:
                db.session.rollback()
                failed += 1
                logger.exception("wa migrate: statement failed: %s", " ".join(stmt.split())[:90])
        logger.info("wa migrate: %d applied, %d failed", applied, failed)
