-- ============================================================================
-- WhatsApp Referral Bot — database schema (canonical schema-of-record).
-- Run ONCE in the Supabase SQL editor before the webhook serves real traffic.
-- Future schema changes: add the ALTER here and run it BEFORE merging the
-- matching model edit (create_all cannot migrate existing tables).
-- See docs/whatsapp-referral-bot-plan.md §4.
-- ============================================================================

-- ---------- PART 1: tables + indexes + RLS on the wa_ tables (REQUIRED) ----------

create table if not exists public.wa_companies (
    id              bigint generated by default as identity primary key,
    name            text not null,
    normalized_name text not null unique,            -- lower(trim(name))
    created_at      timestamptz not null default now()
);

create table if not exists public.wa_users (
    id              bigint generated by default as identity primary key,
    phone           text not null unique,            -- E.164, no 'whatsapp:' prefix
    profile_name    text,
    last_language   text not null default 'en' check (last_language in ('en','he')),
    message_count   integer not null default 0,
    is_blocked      boolean not null default false,
    last_results    jsonb,                           -- array of wa_referral_links.id
    last_results_at timestamptz,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

create table if not exists public.wa_referral_links (
    id                bigint generated by default as identity primary key,
    company_id        bigint not null references public.wa_companies(id),
    submitter_user_id bigint references public.wa_users(id),
    submitter_display text,
    role_title        text,
    url               text not null,
    url_canonical     text not null,
    status            text not null default 'pending'
                      check (status in ('pending','approved','rejected','expired')),
    rejection_reason  text,
    times_sent        integer not null default 0,
    reviewed_at       timestamptz,
    created_at        timestamptz not null default now(),
    updated_at        timestamptz not null default now()
);
create index if not exists ix_wa_links_company_status
    on public.wa_referral_links (company_id, status);
create index if not exists ix_wa_links_pending
    on public.wa_referral_links (status) where status = 'pending';
-- Dedup among LIVE rows only (re-submitting a rejected/expired URL is allowed):
create unique index if not exists uq_wa_links_company_url_active
    on public.wa_referral_links (company_id, url_canonical)
    where status in ('pending','approved');

create table if not exists public.wa_inbound_messages (
    id               bigint generated by default as identity primary key,
    message_sid      text not null unique,            -- Twilio MessageSid (idempotency key)
    from_phone       text not null,
    profile_name     text,
    body             text,
    num_media        integer not null default 0,
    parsed_command   text,                            -- help|add|select|search|ratelimited|error
    response_summary text,
    processing_ms    integer,
    error            text,
    created_at       timestamptz not null default now()
);
create index if not exists ix_wa_inbound_from_created
    on public.wa_inbound_messages (from_phone, created_at);

-- Lock these tables out of the Supabase anon/PostgREST API. RLS with NO policies
-- denies the anon & authenticated roles entirely. The Flask app connects as the
-- table OWNER (the Supabase `postgres` role), which BYPASSES non-forced RLS, so
-- the app is unaffected. NEVER use FORCE ROW LEVEL SECURITY (it would break the app).
alter table public.wa_companies        enable row level security;
alter table public.wa_users            enable row level security;
alter table public.wa_referral_links   enable row level security;
alter table public.wa_inbound_messages enable row level security;


-- ---------- PART 2: close pre-existing PII exposure (OPTIONAL, recommended) -------
-- ig_users stores Instagram access tokens and popup_events is readable via the
-- anon API today. Same owner-bypass logic as Part 1.
--
-- RUN THIS ONLY AFTER Part 1 + a successful bot test (which proves your app
-- connects as owner and is unaffected by RLS), THEN reload ofoodiez.com and
-- confirm the homepage popups still load. If popups vanish, your DB role is NOT
-- the owner — immediately roll back with the two `disable` lines below.
--
-- alter table public.ig_users     enable row level security;
-- alter table public.popup_events enable row level security;
--
-- Rollback (if the homepage popups disappear after Part 2):
-- alter table public.popup_events disable row level security;
-- alter table public.ig_users     disable row level security;
